=== samidakhani/company_employment_tracker/company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.company.org" targetNamespace="http://www.company.org" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Company">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Employee" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element ref="Department" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element ref="Division" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element ref="WorksFor" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="PKEmployee">
			<xs:selector xpath="Employee/EmpId"/>
			<xs:field xpath="."/>
		</xs:key>
		<xs:key name="PKDepartment">
			<xs:selector xpath="Department/DeptId"/>
			<xs:field xpath="."/>
		</xs:key>
		<xs:key name="PKDivision">
			<xs:selector xpath="Division/DivId"/>
			<xs:field xpath="."/>
		</xs:key>
		<xs:key name="PKWorksFor">
			<xs:selector xpath="WorksFor"/>
			<xs:field xpath="DivId"/>
			<xs:field xpath="EmpId"/>
		</xs:key>
		<xs:keyref name="FKDivsionToDepartment" refer="PKDepartment">
			<xs:selector xpath="Division/HouseDeptId"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="FKDivsionToEmployee" refer="PKEmployee">
			<xs:selector xpath="Division/ManagerEmpId"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="FKWorksForToDivision" refer="PKDivision">
			<xs:selector xpath="WorksFor/DivId"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="FKWorksForToEmployee" refer="PKEmployee">
			<xs:selector xpath="WorksFor/EmpId"/>
			<xs:field xpath="."/>
		</xs:keyref>
	</xs:element>
	<xs:element name="Employee">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="EmpId" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="EmpName" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="EmpPhone" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[1-9]{1}\d{2}-\d{3}-\d{4}"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="EmpOffice" type="xs:string" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Department">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DeptId" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[A-Z]{3}"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="DeptName" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="DeptAddr" type="xs:string" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Division">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DivId" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="HouseDeptId" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="ManagerEmpId" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="DivName" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="DivPhone" type="xs:string" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="WorksFor">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DivId" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="EmpId" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="PercentTime" type="xs:int" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== samidakhani/company_employment_tracker/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="company.xsl"?>
<Company xmlns="http://www.company.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.company.org company.xsd">
	<Employee>
		<EmpId>1</EmpId>
		<EmpName>Psmith</EmpName>
		<EmpPhone>243-235-3253</EmpPhone>
		<EmpOffice>LA</EmpOffice>
	</Employee>
	<Employee>
		<EmpId>2</EmpId>
		<EmpName>Wong</EmpName>
		<EmpPhone>224-234-9065</EmpPhone>
		<EmpOffice>LA</EmpOffice>
	</Employee>
	<Employee>
		<EmpId>3</EmpId>
		<EmpName>Jack</EmpName>
		<EmpPhone>243-235-4566</EmpPhone>
		<EmpOffice>LA</EmpOffice>
	</Employee>
	<Employee>
		<EmpId>4</EmpId>
		<EmpName>Anne</EmpName>
		<EmpPhone>324-876-3768</EmpPhone>
		<EmpOffice>LA</EmpOffice>
	</Employee>
	<Employee>
		<EmpId>5</EmpId>
		<EmpName>Ben</EmpName>
		<EmpPhone>453-249-3275</EmpPhone>
		<EmpOffice>LA</EmpOffice>
	</Employee>
	<Employee>
		<EmpId>6</EmpId>
		<EmpName>Monica</EmpName>
		<EmpPhone>935-487-3859</EmpPhone>
		<EmpOffice>LA</EmpOffice>
	</Employee>
	<Employee>
		<EmpId>7</EmpId>
		<EmpName>Jennifer</EmpName>
		<EmpPhone>935-487-3869</EmpPhone>
		<EmpOffice>LA</EmpOffice>
	</Employee>
	<Employee>
		<EmpId>8</EmpId>
		<EmpName>Mary</EmpName>
		<EmpPhone>935-487-3859</EmpPhone>
		<EmpOffice>LA</EmpOffice>
	</Employee>
	<Department>
		<DeptId>ADM</DeptId>
		<DeptName>Admin</DeptName>
		<DeptAddr>LA</DeptAddr>
	</Department>
	<Department>
		<DeptId>FIN</DeptId>
		<DeptName>Finance</DeptName>
		<DeptAddr>LA</DeptAddr>
	</Department>
	<Department>
		<DeptId>SER</DeptId>
		<DeptName>Services</DeptName>
		<DeptAddr>LA</DeptAddr>
	</Department>
	<Department>
		<DeptId>OPR</DeptId>
		<DeptName>Operations</DeptName>
		<DeptAddr>LA</DeptAddr>
	</Department>
	<Department>
		<DeptId>BUS</DeptId>
		<DeptName>Business</DeptName>
		<DeptAddr>LA</DeptAddr>
	</Department>
	<Division>
		<DivId>div1</DivId>
		<HouseDeptId>ADM</HouseDeptId>
		<ManagerEmpId>4</ManagerEmpId>
		<DivName>HR</DivName>
		<DivPhone>346-232-3242</DivPhone>
	</Division>
	<Division>
		<DivId>div2</DivId>
		<HouseDeptId>ADM</HouseDeptId>
		<ManagerEmpId>1</ManagerEmpId>
		<DivName>Recruitment</DivName>
		<DivPhone>346-232-3243</DivPhone>
	</Division>
	<Division>
		<DivId>div3</DivId>
		<HouseDeptId>ADM</HouseDeptId>
		<ManagerEmpId>3</ManagerEmpId>
		<DivName>SysAd</DivName>
		<DivPhone>346-232-3244</DivPhone>
	</Division>
	<Division>
		<DivId>div4</DivId>
		<HouseDeptId>FIN</HouseDeptId>
		<ManagerEmpId>5</ManagerEmpId>
		<DivName>Payroll</DivName>
		<DivPhone>346-232-3245</DivPhone>
	</Division>
	<Division>
		<DivId>div5</DivId>
		<HouseDeptId>FIN</HouseDeptId>
		<ManagerEmpId>5</ManagerEmpId>
		<DivName>Accounting</DivName>
		<DivPhone>346-232-3246</DivPhone>
	</Division>
	<Division>
		<DivId>div6</DivId>
		<HouseDeptId>SER</HouseDeptId>
		<ManagerEmpId>2</ManagerEmpId>
		<DivName>Networking</DivName>
		<DivPhone>346-232-3247</DivPhone>
	</Division>
	<Division>
		<DivId>div7</DivId>
		<HouseDeptId>SER</HouseDeptId>
		<ManagerEmpId>2</ManagerEmpId>
		<DivName>SaaS</DivName>
		<DivPhone>346-232-3248</DivPhone>
	</Division>
	<Division>
		<DivId>div8</DivId>
		<HouseDeptId>SER</HouseDeptId>
		<ManagerEmpId>1</ManagerEmpId>
		<DivName>Security</DivName>
		<DivPhone>346-232-3249</DivPhone>
	</Division>
	<Division>
		<DivId>div9</DivId>
		<HouseDeptId>SER</HouseDeptId>
		<ManagerEmpId>1</ManagerEmpId>
		<DivName>Convergence</DivName>
		<DivPhone>346-232-3250</DivPhone>
	</Division>
	<Division>
		<DivId>div10</DivId>
		<HouseDeptId>OPR</HouseDeptId>
		<ManagerEmpId>1</ManagerEmpId>
		<DivName>Sales</DivName>
		<DivPhone>346-232-3251</DivPhone>
	</Division>
	<Division>
		<DivId>div11</DivId>
		<HouseDeptId>OPR</HouseDeptId>
		<ManagerEmpId>4</ManagerEmpId>
		<DivName>Marketing</DivName>
		<DivPhone>346-232-3252</DivPhone>
	</Division>
	<Division>
		<DivId>div12</DivId>
		<HouseDeptId>OPR</HouseDeptId>
		<ManagerEmpId>4</ManagerEmpId>
		<DivName>Engineering</DivName>
		<DivPhone>346-232-3253</DivPhone>
	</Division>
	<Division>
		<DivId>div13</DivId>
		<HouseDeptId>BUS</HouseDeptId>
		<ManagerEmpId>1</ManagerEmpId>
		<DivName>Business Development</DivName>
		<DivPhone>346-232-3254</DivPhone>
	</Division>
	<Division>
		<DivId>div14</DivId>
		<HouseDeptId>BUS</HouseDeptId>
		<ManagerEmpId>1</ManagerEmpId>
		<DivName>Business Analysis</DivName>
		<DivPhone>346-232-3255</DivPhone>
	</Division>
	<WorksFor>
		<DivId>div1</DivId>
		<EmpId>4</EmpId>
		<PercentTime>60</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div2</DivId>
		<EmpId>4</EmpId>
		<PercentTime>10</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div3</DivId>
		<EmpId>4</EmpId>
		<PercentTime>10</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div13</DivId>
		<EmpId>4</EmpId>
		<PercentTime>5</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div14</DivId>
		<EmpId>4</EmpId>
		<PercentTime>5</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div2</DivId>
		<EmpId>5</EmpId>
		<PercentTime>10</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div3</DivId>
		<EmpId>5</EmpId>
		<PercentTime>10</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div4</DivId>
		<EmpId>5</EmpId>
		<PercentTime>50</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div5</DivId>
		<EmpId>5</EmpId>
		<PercentTime>30</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div2</DivId>
		<EmpId>3</EmpId>
		<PercentTime>20</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div3</DivId>
		<EmpId>3</EmpId>
		<PercentTime>20</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div8</DivId>
		<EmpId>3</EmpId>
		<PercentTime>60</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div2</DivId>
		<EmpId>6</EmpId>
		<PercentTime>10</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div3</DivId>
		<EmpId>6</EmpId>
		<PercentTime>10</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div6</DivId>
		<EmpId>6</EmpId>
		<PercentTime>60</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div7</DivId>
		<EmpId>6</EmpId>
		<PercentTime>20</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div2</DivId>
		<EmpId>1</EmpId>
		<PercentTime>5</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div3</DivId>
		<EmpId>1</EmpId>
		<PercentTime>5</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div6</DivId>
		<EmpId>1</EmpId>
		<PercentTime>15</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div8</DivId>
		<EmpId>1</EmpId>
		<PercentTime>5</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div10</DivId>
		<EmpId>1</EmpId>
		<PercentTime>60</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div13</DivId>
		<EmpId>1</EmpId>
		<PercentTime>5</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div9</DivId>
		<EmpId>1</EmpId>
		<PercentTime>3</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div14</DivId>
		<EmpId>1</EmpId>
		<PercentTime>2</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div2</DivId>
		<EmpId>2</EmpId>
		<PercentTime>10</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div3</DivId>
		<EmpId>2</EmpId>
		<PercentTime>10</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div6</DivId>
		<EmpId>2</EmpId>
		<PercentTime>30</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div7</DivId>
		<EmpId>2</EmpId>
		<PercentTime>10</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div1</DivId>
		<EmpId>2</EmpId>
		<PercentTime>10</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div8</DivId>
		<EmpId>2</EmpId>
		<PercentTime>15</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div4</DivId>
		<EmpId>2</EmpId>
		<PercentTime>15</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div7</DivId>
		<EmpId>7</EmpId>
		<PercentTime>90</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div2</DivId>
		<EmpId>7</EmpId>
		<PercentTime>5</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div3</DivId>
		<EmpId>7</EmpId>
		<PercentTime>5</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div11</DivId>
		<EmpId>8</EmpId>
		<PercentTime>90</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div2</DivId>
		<EmpId>8</EmpId>
		<PercentTime>5</PercentTime>
	</WorksFor>
	<WorksFor>
		<DivId>div3</DivId>
		<EmpId>8</EmpId>
		<PercentTime>5</PercentTime>
	</WorksFor>
</Company>
